const column = (key, header, width = 20) => ({ key, header, width });

export const SHEET_IDS = Object.freeze({
  summary: "summary",
  people: "people",
  studentWorkerAssignments: "student-worker-assignments",
  courseSections: "course-sections",
  sectionMeetings: "section-meetings",
  courses: "courses",
  programs: "programs",
  spaces: "spaces",
  buildings: "buildings",
  terms: "terms",
  roomReservations: "room-reservations",
  baylorAcronyms: "baylor-acronyms",
  emailListPresets: "email-list-presets",
  calendarExceptions: "calendar-exceptions",
  roomGrids: "room-grids",
  roomGridEntries: "room-grid-entries",
});

export const BULK_EXPORT_SHEET_IDS = Object.freeze([
  SHEET_IDS.people,
  SHEET_IDS.studentWorkerAssignments,
  SHEET_IDS.courseSections,
  SHEET_IDS.sectionMeetings,
  SHEET_IDS.courses,
  SHEET_IDS.programs,
  SHEET_IDS.spaces,
  SHEET_IDS.buildings,
  SHEET_IDS.terms,
  SHEET_IDS.roomReservations,
  SHEET_IDS.baylorAcronyms,
  SHEET_IDS.emailListPresets,
  SHEET_IDS.calendarExceptions,
  SHEET_IDS.roomGrids,
  SHEET_IDS.roomGridEntries,
]);

export const SHEET_ORDER = Object.freeze([
  SHEET_IDS.summary,
  ...BULK_EXPORT_SHEET_IDS,
]);

export const TERM_SCOPED_SHEET_IDS = Object.freeze([
  SHEET_IDS.studentWorkerAssignments,
  SHEET_IDS.courseSections,
  SHEET_IDS.sectionMeetings,
  SHEET_IDS.spaces,
  SHEET_IDS.terms,
  SHEET_IDS.roomReservations,
  SHEET_IDS.calendarExceptions,
  SHEET_IDS.roomGrids,
  SHEET_IDS.roomGridEntries,
]);

export const isTermScopedSheet = (sheetId) =>
  TERM_SCOPED_SHEET_IDS.includes(sheetId);

export const SHEET_DEFINITIONS = Object.freeze({
  [SHEET_IDS.summary]: {
    id: SHEET_IDS.summary,
    name: "Summary",
    description: "Export metadata and row counts.",
    columns: [
      column("metric", "Metric", 42),
      column("value", "Value", 52),
    ],
  },
  [SHEET_IDS.people]: {
    id: SHEET_IDS.people,
    name: "People",
    description: "Directory and role status details.",
    columns: [
      column("recordId", "Record ID", 24),
      column("name", "Name", 24),
      column("firstName", "First Name", 16),
      column("lastName", "Last Name", 16),
      column("roles", "Roles", 18),
      column("status", "Status", 12),
      column("inactiveReason", "Inactive Reason", 24),
      column("email", "Email", 28),
      column("alternateEmails", "Alternate Emails", 32),
      column("phone", "Phone", 16),
      column("baylorId", "Baylor ID", 14),
      column("clssInstructorId", "CLSS Instructor ID", 18),
      column("ignitePersonNumber", "Ignite Person Number", 20),
      column("title", "Title", 12),
      column("jobTitle", "Job Title", 24),
      column("department", "Department", 26),
      column("program", "Program", 24),
      column("programCode", "Program Code", 14),
      column("office", "Office", 20),
      column("officeSpaces", "Office Spaces", 28),
      column("primaryBuildings", "Primary Buildings", 26),
      column("isAdjunct", "Adjunct", 12),
      column("directorRoles", "Director Roles", 30),
      column("isFullTime", "Full Time", 12),
      column("isTenured", "Tenured", 12),
      column("hasPhD", "Has PhD", 12),
      column("isRemote", "Remote", 12),
      column("isAlsoFaculty", "Also Faculty", 14),
      column("isAlsoStaff", "Also Staff", 12),
      column("hasNoPhone", "Has No Phone", 14),
      column("hasNoOffice", "Has No Office", 14),
      column("inactiveAt", "Inactive At", 24),
      column("startDate", "Employment Start Date", 20),
      column("endDate", "Employment End Date", 20),
      column("createdAt", "Created At", 24),
      column("updatedAt", "Updated At", 24),
    ],
  },
  [SHEET_IDS.studentWorkerAssignments]: {
    id: SHEET_IDS.studentWorkerAssignments,
    name: "Student Worker Assignments",
    description: "Student worker assignment and schedule details.",
    columns: [
      column("studentId", "Student Record ID", 24),
      column("studentName", "Student Name", 24),
      column("studentEmail", "Student Email", 28),
      column("term", "Semester", 18),
      column("termCode", "Semester Code", 14),
      column("studentStatus", "Student Status", 16),
      column("assignmentId", "Assignment ID", 22),
      column("assignmentStatus", "Assignment Status", 18),
      column("jobTitle", "Job Title", 24),
      column("supervisorId", "Supervisor Record ID", 24),
      column("supervisor", "Supervisor", 24),
      column("supervisorEmail", "Supervisor Email", 28),
      column("hourlyRate", "Hourly Rate", 12),
      column("startDate", "Start Date", 14),
      column("endDate", "End Date", 14),
      column("weeklyHours", "Weekly Hours", 14),
      column("weeklyPay", "Weekly Pay", 14),
      column("weeklySchedule", "Weekly Schedule", 40),
      column("buildings", "Buildings", 24),
    ],
  },
  [SHEET_IDS.courseSections]: {
    id: SHEET_IDS.courseSections,
    name: "Course Sections",
    description: "Section-level operational schedule records.",
    columns: [
      column("recordId", "Record ID", 26),
      column("term", "Semester", 16),
      column("termCode", "Semester Code", 12),
      column("academicYear", "Academic Year", 14),
      column("courseCode", "Course Code", 14),
      column("subjectCode", "Subject Code", 12),
      column("catalogNumber", "Catalog Number", 14),
      column("courseLevel", "Course Level", 12),
      column("courseTitle", "Course Title", 32),
      column("section", "Section", 10),
      column("crn", "CRN", 10),
      column("clssId", "CLSS ID", 24),
      column("status", "Status", 12),
      column("program", "Program", 14),
      column("departmentCode", "Department Code", 18),
      column("credits", "Credits", 10),
      column("instructorIds", "Instructor Record IDs", 32),
      column("instructors", "Instructors", 32),
      column("primaryInstructor", "Primary Instructor", 24),
      column("instructorAssignments", "Instructor Assignments", 42),
      column("instructionMethod", "Instruction Method", 18),
      column("scheduleType", "Schedule Type", 18),
      column("isOnline", "Online", 10),
      column("onlineMode", "Online Mode", 16),
      column("locationType", "Location Type", 14),
      column("spaceIds", "Space IDs", 30),
      column("locations", "Locations", 32),
      column("meetingPatternSummary", "Meeting Pattern Summary", 32),
      column("enrollment", "Enrollment", 12),
      column("maxEnrollment", "Max Enrollment", 14),
      column("openSeats", "Open Seats", 12),
      column("waitCap", "Waitlist Cap", 12),
      column("waitCurrent", "Waitlist Current", 14),
      column("waitAvailable", "Waitlist Available", 16),
      column("reservedSeats", "Reserved Seats", 14),
      column("reservedSeatsEnrollment", "Reserved Seats Filled", 20),
      column("crossListCrns", "Cross-list CRNs", 24),
      column("partOfTerm", "Part of Semester", 14),
      column("customStartDate", "Custom Start Date", 18),
      column("customEndDate", "Custom End Date", 18),
      column("linkGroupId", "Linked Section Group", 24),
      column("createdAt", "Created At", 24),
      column("updatedAt", "Updated At", 24),
    ],
  },
  [SHEET_IDS.sectionMeetings]: {
    id: SHEET_IDS.sectionMeetings,
    name: "Section Meetings",
    description: "Meeting-pattern rows per section.",
    columns: [
      column("scheduleId", "Section Record ID", 26),
      column("meetingIndex", "Meeting Number", 14),
      column("term", "Semester", 16),
      column("termCode", "Semester Code", 12),
      column("courseCode", "Course Code", 14),
      column("section", "Section", 10),
      column("crn", "CRN", 10),
      column("status", "Status", 12),
      column("day", "Day", 8),
      column("startTime", "Start Time", 12),
      column("endTime", "End Time", 12),
      column("startDate", "Meeting Start Date", 18),
      column("endDate", "Meeting End Date", 18),
      column("spaceIds", "Space IDs", 30),
      column("locations", "Locations", 30),
      column("instructorIds", "Instructor Record IDs", 30),
      column("instructors", "Instructors", 30),
    ],
  },
  [SHEET_IDS.courses]: {
    id: SHEET_IDS.courses,
    name: "Courses",
    description: "Course catalog records used by scheduling.",
    columns: [
      column("recordId", "Record ID", 24),
      column("courseCode", "Course Code", 16),
      column("courseTitle", "Course Title", 34),
      column("subjectCode", "Subject Code", 12),
      column("catalogNumber", "Catalog Number", 14),
      column("courseLevel", "Course Level", 12),
      column("credits", "Credits", 10),
      column("program", "Program", 14),
      column("department", "Department", 22),
      column("status", "Status", 12),
      column("createdAt", "Created At", 24),
      column("updatedAt", "Updated At", 24),
    ],
  },
  [SHEET_IDS.programs]: {
    id: SHEET_IDS.programs,
    name: "Programs",
    description: "Program ownership and director (UPD/GPD) assignments.",
    columns: [
      column("recordId", "Record ID", 24),
      column("programName", "Program Name", 26),
      column("programCode", "Program Code", 14),
      column("updNames", "UPD Names", 34),
      column("updCount", "UPD Count", 12),
      column("gpdNames", "GPD Names", 34),
      column("gpdCount", "GPD Count", 12),
      column("updIds", "UPD Record IDs", 34),
      column("gpdIds", "GPD Record IDs", 34),
      column("directorIds", "Director Record IDs", 34),
      column("status", "Status", 12),
      column("createdAt", "Created At", 24),
      column("updatedAt", "Updated At", 24),
    ],
  },
  [SHEET_IDS.spaces]: {
    id: SHEET_IDS.spaces,
    name: "Spaces",
    description: "Unified room and office inventory.",
    columns: [
      column("recordId", "Record ID", 24),
      column("spaceKey", "Space Key", 20),
      column("displayName", "Display Name", 28),
      column("buildingCode", "Building Code", 14),
      column("buildingName", "Building Name", 24),
      column("spaceNumber", "Space Number", 14),
      column("type", "Type", 14),
      column("capacity", "Capacity", 10),
      column("equipment", "Equipment", 30),
      column("status", "Status", 12),
      column("isReservable", "Reservable", 12),
      column("scheduledSectionsCount", "Scheduled Sections Count", 22),
      column("assignedOfficesCount", "Assigned Offices Count", 22),
      column("notes", "Notes", 28),
      column("createdBy", "Created By", 28),
      column("deletedAt", "Deleted At", 24),
      column("createdAt", "Created At", 24),
      column("updatedAt", "Updated At", 24),
    ],
  },
  [SHEET_IDS.buildings]: {
    id: SHEET_IDS.buildings,
    name: "Buildings",
    description: "Building configuration and active space totals.",
    columns: [
      column("recordId", "Record ID", 20),
      column("code", "Code", 14),
      column("displayName", "Display Name", 24),
      column("aliases", "Aliases", 36),
      column("campus", "Campus", 20),
      column("address", "Address", 34),
      column("status", "Status", 12),
      column("activeSpaceCount", "Active Space Count", 18),
      column("createdAt", "Created At", 24),
      column("updatedAt", "Updated At", 24),
    ],
  },
  [SHEET_IDS.terms]: {
    id: SHEET_IDS.terms,
    name: "Semesters",
    description: "Semester lifecycle and scoped section counts.",
    columns: [
      column("recordId", "Record ID", 20),
      column("term", "Semester", 18),
      column("termCode", "Semester Code", 12),
      column("status", "Status", 12),
      column("locked", "Locked", 10),
      column("startDate", "Start Date", 14),
      column("endDate", "End Date", 14),
      column("sectionCount", "Section Count", 14),
      column("createdAt", "Created At", 24),
      column("updatedAt", "Updated At", 24),
    ],
  },
  [SHEET_IDS.roomReservations]: {
    id: SHEET_IDS.roomReservations,
    name: "Room Reservations",
    description: "Department room reservations.",
    columns: [
      column("recordId", "Record ID", 24),
      column("status", "Status", 12),
      column("date", "Date", 14),
      column("startTime", "Start Time", 12),
      column("endTime", "End Time", 12),
      column("startMinutes", "Start Minutes", 14),
      column("endMinutes", "End Minutes", 14),
      column("title", "Title", 30),
      column("purpose", "Purpose", 36),
      column("headcount", "Headcount", 12),
      column("spaceKey", "Space ID", 24),
      column("roomDisplay", "Room", 24),
      column("buildingCode", "Building Code", 14),
      column("buildingDisplayName", "Building", 24),
      column("requesterName", "Requester Name", 24),
      column("requesterEmail", "Requester Email", 28),
      column("createdBy", "Created By", 28),
      column("createdAt", "Created At", 24),
    ],
  },
  [SHEET_IDS.baylorAcronyms]: {
    id: SHEET_IDS.baylorAcronyms,
    name: "Baylor Acronyms",
    description: "Shared acronym directory.",
    columns: [
      column("recordId", "Record ID", 24),
      column("acronym", "Acronym", 14),
      column("standsFor", "Stands For", 34),
      column("category", "Category", 20),
      column("description", "Description", 44),
    ],
  },
  [SHEET_IDS.emailListPresets]: {
    id: SHEET_IDS.emailListPresets,
    name: "Email List Presets",
    description: "Saved reusable directory selections.",
    columns: [
      column("recordId", "Record ID", 24),
      column("name", "Preset Name", 28),
      column("personIds", "Person Record IDs", 44),
      column("people", "People", 44),
      column("emails", "Emails", 44),
      column("personCount", "Person Count", 14),
      column("createdBy", "Created By", 28),
      column("updatedBy", "Updated By", 28),
      column("createdAt", "Created At", 24),
      column("updatedAt", "Updated At", 24),
    ],
  },
  [SHEET_IDS.calendarExceptions]: {
    id: SHEET_IDS.calendarExceptions,
    name: "Calendar Exceptions",
    description: "Shared no-class dates used by room calendar exports.",
    columns: [
      column("recordId", "Settings Record ID", 24),
      column("term", "Semester", 18),
      column("date", "Date", 14),
      column("label", "Label", 34),
      column("updatedAt", "Updated At", 24),
    ],
  },
  [SHEET_IDS.roomGrids]: {
    id: SHEET_IDS.roomGrids,
    name: "Room Grids",
    description: "Saved printable room grid templates.",
    columns: [
      column("recordId", "Record ID", 24),
      column("title", "Title", 32),
      column("kind", "Kind", 12),
      column("schemaVersion", "Schema Version", 14),
      column("building", "Building", 18),
      column("room", "Room", 14),
      column("dayPattern", "Day Pattern", 14),
      column("semester", "Semester", 16),
      column("folder", "Folder", 24),
      column("tags", "Tags", 30),
      column("favorite", "Favorite", 12),
      column("source", "Source", 14),
      column("entryCount", "Entry Count", 12),
      column("layout", "Layout Settings", 48),
      column("visibility", "Visible Fields", 48),
      column("createdAt", "Created At", 24),
      column("updatedAt", "Updated At", 24),
      column("hasTemplate", "Has Template", 14),
    ],
  },
  [SHEET_IDS.roomGridEntries]: {
    id: SHEET_IDS.roomGridEntries,
    name: "Room Grid Entries",
    description: "Class blocks stored in Schedule Grid Studio templates.",
    columns: [
      column("gridId", "Grid Record ID", 24),
      column("gridTitle", "Grid Title", 30),
      column("entryId", "Entry ID", 28),
      column("course", "Course", 16),
      column("section", "Section", 10),
      column("instructor", "Instructor", 28),
      column("days", "Days", 14),
      column("start", "Start Time", 12),
      column("end", "End Time", 12),
      column("hidden", "Hidden", 10),
      column("detailLevel", "Detail Level", 14),
      column("blockColor", "Block Color", 14),
      column("note", "Note", 36),
    ],
  },
});

export const INDIVIDUAL_EXPORT_OPTIONS = Object.freeze([
  {
    id: SHEET_IDS.people,
    label: "People",
    description: "Directory records, role flags, and contact fields.",
    sheetIds: [SHEET_IDS.people],
  },
  {
    id: SHEET_IDS.studentWorkerAssignments,
    label: "Student Worker Assignments",
    description: "Student worker jobs, schedules, and supervisor details.",
    sheetIds: [SHEET_IDS.studentWorkerAssignments],
  },
  {
    id: SHEET_IDS.courseSections,
    label: "Course Sections",
    description: "Section records and high-level scheduling details.",
    sheetIds: [SHEET_IDS.courseSections],
  },
  {
    id: SHEET_IDS.sectionMeetings,
    label: "Section Meetings",
    description: "Meeting-pattern rows by day and time.",
    sheetIds: [SHEET_IDS.sectionMeetings],
  },
  {
    id: SHEET_IDS.courses,
    label: "Courses",
    description: "Catalog-level course definitions.",
    sheetIds: [SHEET_IDS.courses],
  },
  {
    id: SHEET_IDS.programs,
    label: "Programs",
    description: "Program list and director (UPD/GPD) assignments.",
    sheetIds: [SHEET_IDS.programs],
  },
  {
    id: SHEET_IDS.spaces,
    label: "Spaces",
    description: "Room and office inventory with utilization counts.",
    sheetIds: [SHEET_IDS.spaces],
  },
  {
    id: SHEET_IDS.buildings,
    label: "Buildings",
    description: "Building metadata and alias configuration.",
    sheetIds: [SHEET_IDS.buildings],
  },
  {
    id: SHEET_IDS.terms,
    label: "Semesters",
    description: "Semester metadata and section counts.",
    sheetIds: [SHEET_IDS.terms],
  },
  {
    id: SHEET_IDS.roomReservations,
    label: "Room Reservations",
    description: "Department room bookings and requester details.",
    sheetIds: [SHEET_IDS.roomReservations],
  },
  {
    id: SHEET_IDS.baylorAcronyms,
    label: "Baylor Acronyms",
    description: "The shared acronym directory.",
    sheetIds: [SHEET_IDS.baylorAcronyms],
  },
  {
    id: SHEET_IDS.emailListPresets,
    label: "Email List Presets",
    description: "Saved reusable directory selections.",
    sheetIds: [SHEET_IDS.emailListPresets],
  },
  {
    id: SHEET_IDS.calendarExceptions,
    label: "Calendar Exceptions",
    description: "Shared no-class dates used by room calendar exports.",
    sheetIds: [SHEET_IDS.calendarExceptions],
  },
  {
    id: SHEET_IDS.roomGrids,
    label: "Room Grids",
    description: "Saved room-grid exports and templates.",
    sheetIds: [SHEET_IDS.roomGrids, SHEET_IDS.roomGridEntries],
  },
]);

export const getSheetDefinition = (sheetId) => SHEET_DEFINITIONS[sheetId] || null;
