const column = (key, header, width = 20) => ({ key, header, width });

export const SHEET_IDS = Object.freeze({
  summary: "summary",
  people: "people",
  studentWorkerAssignments: "student-worker-assignments",
  courseSections: "course-sections",
  sectionMeetings: "section-meetings",
  courses: "courses",
  programs: "programs",
  spaces: "spaces",
  buildings: "buildings",
  terms: "terms",
  roomGrids: "room-grids",
});

export const BULK_EXPORT_SHEET_IDS = Object.freeze([
  SHEET_IDS.people,
  SHEET_IDS.studentWorkerAssignments,
  SHEET_IDS.courseSections,
  SHEET_IDS.sectionMeetings,
  SHEET_IDS.courses,
  SHEET_IDS.programs,
  SHEET_IDS.spaces,
  SHEET_IDS.buildings,
  SHEET_IDS.terms,
  SHEET_IDS.roomGrids,
]);

export const SHEET_ORDER = Object.freeze([
  SHEET_IDS.summary,
  ...BULK_EXPORT_SHEET_IDS,
]);

export const TECHNICAL_FIELD_EXCLUSIONS = Object.freeze([
  "identityKey",
  "identityKeys",
  "identitySource",
  "createdAt",
  "updatedAt",
  "mergedInto",
  "rawHtml",
  "html",
]);

export const SHEET_DEFINITIONS = Object.freeze({
  [SHEET_IDS.summary]: {
    id: SHEET_IDS.summary,
    name: "Summary",
    description: "Export metadata and row counts.",
    columns: [
      column("metric", "Metric", 42),
      column("value", "Value", 52),
    ],
  },
  [SHEET_IDS.people]: {
    id: SHEET_IDS.people,
    name: "People",
    description: "Directory and role status details.",
    columns: [
      column("name", "Name", 24),
      column("firstName", "First Name", 16),
      column("lastName", "Last Name", 16),
      column("roles", "Roles", 18),
      column("status", "Status", 12),
      column("inactiveReason", "Inactive Reason", 24),
      column("email", "Email", 28),
      column("phone", "Phone", 16),
      column("baylorId", "Baylor ID", 14),
      column("clssInstructorId", "CLSS Instructor ID", 18),
      column("title", "Title", 12),
      column("jobTitle", "Job Title", 24),
      column("department", "Department", 26),
      column("program", "Program", 24),
      column("office", "Office", 20),
      column("officeSpaces", "Office Spaces", 28),
      column("isAdjunct", "Adjunct", 12),
      column("isUPD", "UPD", 10),
      column("isFullTime", "Full Time", 12),
      column("isTenured", "Tenured", 12),
      column("isRemote", "Remote", 12),
      column("hasNoPhone", "Has No Phone", 14),
      column("hasNoOffice", "Has No Office", 14),
    ],
  },
  [SHEET_IDS.studentWorkerAssignments]: {
    id: SHEET_IDS.studentWorkerAssignments,
    name: "Student Worker Assignments",
    description: "Student worker assignment and schedule details.",
    columns: [
      column("studentName", "Student Name", 24),
      column("studentEmail", "Student Email", 28),
      column("studentStatus", "Student Status", 16),
      column("assignmentStatus", "Assignment Status", 18),
      column("jobTitle", "Job Title", 24),
      column("supervisor", "Supervisor", 24),
      column("supervisorEmail", "Supervisor Email", 28),
      column("hourlyRate", "Hourly Rate", 12),
      column("startDate", "Start Date", 14),
      column("endDate", "End Date", 14),
      column("weeklyHours", "Weekly Hours", 14),
      column("weeklySchedule", "Weekly Schedule", 40),
      column("buildings", "Buildings", 24),
    ],
  },
  [SHEET_IDS.courseSections]: {
    id: SHEET_IDS.courseSections,
    name: "Course Sections",
    description: "Section-level operational schedule records.",
    columns: [
      column("term", "Term", 16),
      column("termCode", "Term Code", 12),
      column("courseCode", "Course Code", 14),
      column("courseTitle", "Course Title", 32),
      column("section", "Section", 10),
      column("crn", "CRN", 10),
      column("status", "Status", 12),
      column("program", "Program", 14),
      column("credits", "Credits", 10),
      column("instructors", "Instructors", 32),
      column("primaryInstructor", "Primary Instructor", 24),
      column("instructionMethod", "Instruction Method", 18),
      column("scheduleType", "Schedule Type", 18),
      column("locationType", "Location Type", 14),
      column("locations", "Locations", 32),
      column("meetingPatternSummary", "Meeting Pattern Summary", 32),
      column("enrollment", "Enrollment", 12),
      column("maxEnrollment", "Max Enrollment", 14),
      column("waitCap", "Waitlist Cap", 12),
      column("waitCurrent", "Waitlist Current", 14),
      column("partOfTerm", "Part of Term", 14),
      column("customStartDate", "Custom Start Date", 18),
      column("customEndDate", "Custom End Date", 18),
    ],
  },
  [SHEET_IDS.sectionMeetings]: {
    id: SHEET_IDS.sectionMeetings,
    name: "Section Meetings",
    description: "Meeting-pattern rows per section.",
    columns: [
      column("term", "Term", 16),
      column("termCode", "Term Code", 12),
      column("courseCode", "Course Code", 14),
      column("section", "Section", 10),
      column("crn", "CRN", 10),
      column("status", "Status", 12),
      column("day", "Day", 8),
      column("startTime", "Start Time", 12),
      column("endTime", "End Time", 12),
      column("locations", "Locations", 30),
      column("instructors", "Instructors", 30),
    ],
  },
  [SHEET_IDS.courses]: {
    id: SHEET_IDS.courses,
    name: "Courses",
    description: "Course catalog records used by scheduling.",
    columns: [
      column("courseCode", "Course Code", 16),
      column("courseTitle", "Course Title", 34),
      column("subjectCode", "Subject Code", 12),
      column("catalogNumber", "Catalog Number", 14),
      column("credits", "Credits", 10),
      column("program", "Program", 14),
      column("department", "Department", 22),
      column("status", "Status", 12),
    ],
  },
  [SHEET_IDS.programs]: {
    id: SHEET_IDS.programs,
    name: "Programs",
    description: "Program ownership and UPD assignments.",
    columns: [
      column("programName", "Program Name", 26),
      column("programCode", "Program Code", 14),
      column("updNames", "UPD Names", 34),
      column("updCount", "UPD Count", 12),
      column("status", "Status", 12),
    ],
  },
  [SHEET_IDS.spaces]: {
    id: SHEET_IDS.spaces,
    name: "Spaces",
    description: "Unified room and office inventory.",
    columns: [
      column("spaceKey", "Space Key", 20),
      column("displayName", "Display Name", 28),
      column("buildingCode", "Building Code", 14),
      column("buildingName", "Building Name", 24),
      column("spaceNumber", "Space Number", 14),
      column("type", "Type", 14),
      column("capacity", "Capacity", 10),
      column("equipment", "Equipment", 30),
      column("status", "Status", 12),
      column("scheduledSectionsCount", "Scheduled Sections Count", 22),
      column("assignedOfficesCount", "Assigned Offices Count", 22),
      column("notes", "Notes", 28),
    ],
  },
  [SHEET_IDS.buildings]: {
    id: SHEET_IDS.buildings,
    name: "Buildings",
    description: "Building configuration and active space totals.",
    columns: [
      column("code", "Code", 14),
      column("displayName", "Display Name", 24),
      column("aliases", "Aliases", 36),
      column("campus", "Campus", 20),
      column("address", "Address", 34),
      column("status", "Status", 12),
      column("activeSpaceCount", "Active Space Count", 18),
    ],
  },
  [SHEET_IDS.terms]: {
    id: SHEET_IDS.terms,
    name: "Terms",
    description: "Term lifecycle and scoped section counts.",
    columns: [
      column("term", "Term", 18),
      column("termCode", "Term Code", 12),
      column("status", "Status", 12),
      column("locked", "Locked", 10),
      column("startDate", "Start Date", 14),
      column("endDate", "End Date", 14),
      column("sectionCount", "Section Count", 14),
    ],
  },
  [SHEET_IDS.roomGrids]: {
    id: SHEET_IDS.roomGrids,
    name: "Room Grids",
    description: "Saved printable room grid templates.",
    columns: [
      column("title", "Title", 32),
      column("building", "Building", 18),
      column("room", "Room", 14),
      column("dayPattern", "Day Pattern", 14),
      column("semester", "Semester", 16),
      column("createdAt", "Created At", 24),
      column("hasTemplate", "Has Template", 14),
    ],
  },
});

export const INDIVIDUAL_EXPORT_OPTIONS = Object.freeze([
  {
    id: SHEET_IDS.people,
    label: "People",
    description: "Directory records, role flags, and contact fields.",
    sheetIds: [SHEET_IDS.people],
  },
  {
    id: SHEET_IDS.studentWorkerAssignments,
    label: "Student Worker Assignments",
    description: "Student worker jobs, schedules, and supervisor details.",
    sheetIds: [SHEET_IDS.studentWorkerAssignments],
  },
  {
    id: SHEET_IDS.courseSections,
    label: "Course Sections",
    description: "Section records and high-level scheduling details.",
    sheetIds: [SHEET_IDS.courseSections],
  },
  {
    id: SHEET_IDS.sectionMeetings,
    label: "Section Meetings",
    description: "Meeting-pattern rows by day and time.",
    sheetIds: [SHEET_IDS.sectionMeetings],
  },
  {
    id: SHEET_IDS.courses,
    label: "Courses",
    description: "Catalog-level course definitions.",
    sheetIds: [SHEET_IDS.courses],
  },
  {
    id: SHEET_IDS.programs,
    label: "Programs",
    description: "Program list and UPD assignments.",
    sheetIds: [SHEET_IDS.programs],
  },
  {
    id: SHEET_IDS.spaces,
    label: "Spaces",
    description: "Room and office inventory with utilization counts.",
    sheetIds: [SHEET_IDS.spaces],
  },
  {
    id: SHEET_IDS.buildings,
    label: "Buildings",
    description: "Building metadata and alias configuration.",
    sheetIds: [SHEET_IDS.buildings],
  },
  {
    id: SHEET_IDS.terms,
    label: "Terms",
    description: "Term metadata and section counts.",
    sheetIds: [SHEET_IDS.terms],
  },
  {
    id: SHEET_IDS.roomGrids,
    label: "Room Grids",
    description: "Saved room-grid exports and templates.",
    sheetIds: [SHEET_IDS.roomGrids],
  },
]);

export const getSheetDefinition = (sheetId) => SHEET_DEFINITIONS[sheetId] || null;

export const getSheetHeaders = (sheetId) => {
  const definition = getSheetDefinition(sheetId);
  if (!definition) return [];
  return definition.columns.map((columnDef) => columnDef.header);
};

export default {
  SHEET_IDS,
  BULK_EXPORT_SHEET_IDS,
  SHEET_ORDER,
  SHEET_DEFINITIONS,
  INDIVIDUAL_EXPORT_OPTIONS,
  getSheetDefinition,
  getSheetHeaders,
};
