import {
  Home,
  LayoutGrid,
  Radio,
  Users,
  Mail,
  MapPin,
  GraduationCap,
  FileText,
  ClipboardList,
  BookOpen,
  Settings,
  Calendar,
  Building,
  UserCheck,
  BarChart3,
  ExternalLink,
  Thermometer,
  Shield,
  Sparkles,
  Target,
  Clock,
  Activity,
  Gauge,
  ArrowLeftRight,
} from "lucide-react";

export const navigationItems = [
  {
    id: "home",
    label: "Home",
    icon: Home,
    description: "Launchpad and live views.",
    children: [
      {
        id: "dashboard",
        label: "Dashboard",
        path: "dashboard",
        canonicalId: "dashboard",
        description: "Return to the launchpad.",
        icon: LayoutGrid,
      },
      {
        id: "live-view",
        label: "Today",
        path: "live-view",
        canonicalId: "live-view",
        description: "Open the live view for today.",
        icon: Radio,
      },
    ],
  },
  {
    id: "people",
    label: "People",
    icon: Users,
    description: "Directory and people records.",
    children: [
      {
        id: "people-directory",
        label: "Directory",
        path: "people/directory",
        canonicalId: "people/directory",
        description: "Faculty, staff, and student worker contacts.",
        icon: Users,
      },
      {
        id: "email-lists",
        label: "Email Lists",
        path: "people/email-lists",
        canonicalId: "people/email-lists",
        description: "Department email groups and exports.",
        icon: Mail,
      },
      {
        id: "office-directory",
        label: "Offices",
        path: "people/offices",
        canonicalId: "people/offices",
        description: "Office locations and assignments.",
        icon: MapPin,
      },
      {
        id: "programs",
        label: "Programs & Directors",
        path: "people/programs",
        canonicalId: "people/programs",
        description: "Programs, directors (UPD/GPD), and affiliations.",
        icon: GraduationCap,
      },
      {
        id: "baylor-ids",
        label: "Baylor IDs",
        path: "people/baylor-ids",
        canonicalId: "people/baylor-ids",
        description: "Lookup and manage Baylor IDs.",
        icon: FileText,
      },
    ],
  },
  {
    id: "workflows",
    label: "Workflows",
    icon: ClipboardList,
    description: "Formal workflows and approvals.",
    children: [
      {
        id: "paf-workflow",
        label: "PAF Workflow",
        path: "workflows/paf",
        canonicalId: "workflows/paf",
        description: "Personnel action form workflow.",
        icon: ClipboardList,
      },
    ],
  },
  {
    id: "courses",
    label: "Courses",
    icon: GraduationCap,
    description: "Course browsing and management.",
    children: [
      {
        id: "course-browser",
        label: "Browse",
        path: "courses/browse",
        canonicalId: "courses/browse",
        description: "Browse course offerings.",
        icon: BookOpen,
      },
      {
        id: "course-manage",
        label: "Manage",
        path: "courses/manage",
        canonicalId: "courses/manage",
        description: "Manage course assignments.",
        icon: Settings,
      },
    ],
  },
  {
    id: "scheduling",
    label: "Scheduling",
    icon: Calendar,
    description: "Rooms, faculty, and student workers.",
    children: [
      {
        id: "faculty-schedules",
        label: "Faculty",
        path: "scheduling/faculty",
        canonicalId: "scheduling/faculty",
        description: "Faculty schedules and availability.",
        icon: Calendar,
        sidebarChildren: [
          {
            id: "faculty-compare-schedules",
            label: "Compare Schedules",
            path: "scheduling/faculty?tab=compare",
            description: "Compare faculty schedules side by side.",
            icon: ArrowLeftRight,
            defaultForParent: true,
          },
          {
            id: "faculty-availability",
            label: "Availability",
            path: "scheduling/faculty?tab=availability",
            description: "Find an individual faculty member's availability.",
            icon: Clock,
          },
          {
            id: "faculty-group-meetings",
            label: "Group Meetings",
            path: "scheduling/faculty?tab=meetings",
            description: "Find shared meeting times for a group.",
            icon: Users,
          },
        ],
      },
      {
        id: "room-schedules",
        label: "Rooms",
        path: "scheduling/rooms",
        canonicalId: "scheduling/rooms",
        description: "Room schedules and availability.",
        icon: Building,
        sidebarChildren: [
          {
            id: "rooms-browse",
            label: "Browse",
            path: "scheduling/rooms?tab=browse",
            description: "Browse room schedules and availability.",
            icon: Building,
            defaultForParent: true,
          },
          {
            id: "rooms-reservations",
            label: "Reservations",
            path: "scheduling/rooms?tab=reservations",
            description: "Manage room reservation requests.",
            icon: ClipboardList,
          },
        ],
      },
      {
        id: "room-calendar-export",
        label: "Room Calendar Export",
        path: "tools/outlook-export",
        canonicalId: "tools/outlook-export",
        description: "Export rooms to Outlook.",
        icon: Calendar,
      },
      {
        id: "room-grids",
        label: "Room Grids",
        path: "tools/room-grid-generator",
        canonicalId: "tools/room-grid-generator",
        description: "Generate room grid schedules.",
        icon: LayoutGrid,
      },
      {
        id: "student-schedules",
        label: "Student Workers",
        path: "scheduling/student-workers",
        canonicalId: "scheduling/student-workers",
        description: "Student worker schedules.",
        icon: UserCheck,
        sidebarChildren: [
          {
            id: "student-worker-schedules",
            label: "Schedules",
            path: "scheduling/student-workers?tab=schedule",
            description: "Review student worker schedules.",
            icon: UserCheck,
            defaultForParent: true,
          },
          {
            id: "student-worker-payroll",
            label: "Payroll",
            path: "scheduling/student-workers?tab=payroll",
            description: "Review payroll insights for student workers.",
            icon: BarChart3,
          },
        ],
      },
    ],
  },
  {
    id: "analytics",
    label: "Analytics",
    icon: BarChart3,
    description: "Insights and reporting.",
    children: [
      {
        id: "department-insights",
        label: "Department Insights",
        path: "analytics/department-insights",
        canonicalId: "analytics/department-insights",
        description: "Department-level reporting.",
        icon: BarChart3,
      },
      {
        id: "student-worker-analytics",
        label: "Student Worker Analytics",
        path: "analytics/student-worker-analytics",
        canonicalId: "analytics/student-worker-analytics",
        description: "Student worker analytics.",
        icon: BarChart3,
      },
      {
        id: "enrollment-capacity",
        label: "Enrollment & Capacity",
        path: "analytics/enrollment-capacity",
        canonicalId: "analytics/enrollment-capacity",
        description: "Capacity flags and actionable enrollment insights.",
        icon: Gauge,
      },
      {
        id: "term-comparison",
        label: "Semester Comparison",
        path: "analytics/term-comparison",
        canonicalId: "analytics/term-comparison",
        description: "What changed between two semesters of the schedule.",
        icon: ArrowLeftRight,
      },
    ],
  },
  {
    id: "help",
    label: "Help & Resources",
    icon: BookOpen,
    description: "Guides and reference materials.",
    children: [
      {
        id: "help",
        label: "Tutorials",
        path: "help/tutorials",
        canonicalId: "help/tutorials",
        description: "Guided walkthroughs and tips.",
        icon: BookOpen,
      },
      {
        id: "baylor-systems",
        label: "Baylor Systems",
        path: "help/baylor-systems",
        canonicalId: "help/baylor-systems",
        description: "Links to Baylor systems.",
        icon: ExternalLink,
      },
      {
        id: "baylor-acronyms",
        label: "Acronyms",
        path: "help/acronyms",
        canonicalId: "help/acronyms",
        description: "Common terms and abbreviations.",
        icon: FileText,
      },
    ],
  },
  {
    id: "facilities",
    label: "Facilities",
    icon: Building,
    description: "Spaces, buildings, and temperature.",
    children: [
      {
        id: "space-management",
        label: "Spaces",
        path: "facilities/spaces",
        canonicalId: "facilities/spaces",
        description: "Space inventory and details.",
        icon: MapPin,
      },
      {
        id: "building-management",
        label: "Buildings",
        path: "facilities/buildings",
        canonicalId: "facilities/buildings",
        description: "Building information.",
        icon: Building,
      },
      {
        id: "temperature-monitoring",
        label: "Temperature",
        path: "facilities/temperature",
        canonicalId: "facilities/temperature",
        description: "Temperature monitoring.",
        icon: Thermometer,
      },
    ],
  },
  {
    id: "administration",
    label: "Administration",
    icon: Shield,
    description: "Imports, configuration, and access.",
    children: [
      {
        id: "smart-import",
        label: "Import Wizard",
        path: "admin-tools/import-wizard",
        canonicalId: "admin-tools/import-wizard",
        description: "Import schedules and people data.",
        icon: Sparkles,
      },
      {
        id: "crn-tools",
        label: "CRN Quality Tools",
        path: "admin-tools/crn-tools",
        canonicalId: "admin-tools/crn-tools",
        description: "Course data quality checks.",
        icon: Target,
      },
      {
        id: "accounts",
        label: "Accounts",
        path: "admin/accounts",
        canonicalId: "admin/accounts",
        ownerOnly: true,
        description: "Owner-only approval of sign-ups and account access.",
        icon: Shield,
      },
      {
        id: "app-settings",
        label: "App Settings",
        path: "admin/settings",
        canonicalId: "admin/settings",
        description: "Application configuration.",
        icon: Settings,
      },
      {
        id: "recent-changes",
        label: "Recent Changes",
        path: "admin/recent-changes",
        canonicalId: "admin/recent-changes",
        description: "Review recent updates.",
        icon: Clock,
      },
      {
        id: "user-activity",
        label: "User Activity",
        path: "admin/user-activity",
        canonicalId: "admin/user-activity",
        ownerOnly: true,
        description: "Owner-only timeline of in-app user activity.",
        icon: Activity,
      },
      {
        id: "data-hygiene",
        label: "Data Health Check",
        path: "admin/data-hygiene",
        canonicalId: "admin/data-hygiene",
        description: "Guided checks, routine cleanup, and support tools.",
        icon: FileText,
      },
      {
        id: "data-exports",
        label: "Data Exports",
        path: "admin/data-exports",
        canonicalId: "admin/data-exports",
        description: "Export operational data to Excel workbooks.",
        icon: FileText,
      },
    ],
  },
];
