import {
  Home,
  LayoutGrid,
  Radio,
  Users,
  Mail,
  MapPin,
  GraduationCap,
  FileText,
  ClipboardList,
  BookOpen,
  Settings,
  Calendar,
  Building,
  UserCheck,
  BarChart3,
  ExternalLink,
  Thermometer,
  Shield,
  Sparkles,
  Target,
  Clock,
} from "lucide-react";

export const navigationItems = [
  {
    id: "home",
    label: "Home",
    icon: Home,
    description: "Launchpad and live views.",
    children: [
      {
        id: "dashboard",
        label: "Dashboard",
        path: "dashboard",
        canonicalId: "dashboard",
        description: "Return to the launchpad.",
        icon: LayoutGrid,
      },
      {
        id: "live-view",
        label: "Today",
        path: "live-view",
        canonicalId: "live-view",
        description: "Open the live view for today.",
        icon: Radio,
      },
    ],
  },
  {
    id: "people",
    label: "People",
    icon: Users,
    description: "Directory and people records.",
    children: [
      {
        id: "people-directory",
        label: "Directory",
        path: "people/directory",
        canonicalId: "people/directory",
        description: "Faculty, staff, and student worker contacts.",
        icon: Users,
      },
      {
        id: "email-lists",
        label: "Email Lists",
        path: "people/email-lists",
        canonicalId: "people/email-lists",
        description: "Department email groups and exports.",
        icon: Mail,
      },
      {
        id: "office-directory",
        label: "Offices",
        path: "people/offices",
        canonicalId: "people/offices",
        description: "Office locations and assignments.",
        icon: MapPin,
      },
      {
        id: "programs",
        label: "Programs",
        path: "people/programs",
        canonicalId: "people/programs",
        description: "Programs, UPDs, and affiliations.",
        icon: GraduationCap,
      },
      {
        id: "baylor-ids",
        label: "Baylor IDs",
        path: "people/baylor-ids",
        canonicalId: "people/baylor-ids",
        permissions: {
          // Inherit from parent or specify if needed.
          // BaylorIDManager checks permissions internally ("people/baylor-id-manager")
        },
        description: "Lookup and manage Baylor IDs.",
        icon: FileText,
      },
    ],
  },
  {
    id: "workflows",
    label: "Workflows",
    icon: ClipboardList,
    description: "Formal workflows and approvals.",
    children: [
      {
        id: "paf-workflow",
        label: "PAF Workflow",
        path: "workflows/paf",
        canonicalId: "workflows/paf",
        accessId: "people/directory",
        description: "Personnel action form workflow.",
        icon: ClipboardList,
      },
    ],
  },
  {
    id: "courses",
    label: "Courses",
    icon: GraduationCap,
    description: "Course browsing and management.",
    children: [
      {
        id: "course-browser",
        label: "Browse",
        path: "courses/browse",
        canonicalId: "courses/browse",
        description: "Browse course offerings.",
        icon: BookOpen,
      },
      {
        id: "course-manage",
        label: "Manage",
        path: "courses/manage",
        canonicalId: "courses/manage",
        permissions: { hideFromRoles: ["faculty"] },
        description: "Manage course assignments.",
        icon: Settings,
      },
    ],
  },
  {
    id: "scheduling",
    label: "Scheduling",
    icon: Calendar,
    description: "Rooms, faculty, and student workers.",
    children: [
      {
        id: "faculty-schedules",
        label: "Faculty",
        path: "scheduling/faculty",
        canonicalId: "scheduling/faculty",
        description: "Faculty schedules and availability.",
        icon: Calendar,
      },
      {
        id: "room-schedules",
        label: "Rooms",
        path: "scheduling/rooms",
        canonicalId: "scheduling/rooms",
        description: "Room schedules and availability.",
        icon: Building,
      },
      {
        id: "room-calendar-export",
        label: "Room Calendar Export",
        path: "tools/outlook-export",
        canonicalId: "tools/outlook-export",
        description: "Export rooms to Outlook.",
        icon: Calendar,
      },
      {
        id: "room-grids",
        label: "Room Grids",
        path: "tools/room-grid-generator",
        canonicalId: "tools/room-grid-generator",
        description: "Generate room grid schedules.",
        icon: LayoutGrid,
      },
      {
        id: "student-schedules",
        label: "Student Workers",
        path: "scheduling/student-workers",
        canonicalId: "scheduling/student-workers",
        permissions: {
          hideFromRoles: ["faculty"],
        },
        description: "Student worker schedules.",
        icon: UserCheck,
      },
    ],
  },
  {
    id: "analytics",
    label: "Analytics",
    icon: BarChart3,
    description: "Insights and reporting.",
    children: [
      {
        id: "department-insights",
        label: "Department Insights",
        path: "analytics/department-insights",
        canonicalId: "analytics/department-insights",
        permissions: {
          hideFromRoles: ["faculty"],
        },
        description: "Department-level reporting.",
        icon: BarChart3,
      },
      {
        id: "student-worker-analytics",
        label: "Student Worker Analytics",
        path: "analytics/student-worker-analytics",
        canonicalId: "analytics/student-worker-analytics",
        permissions: {
          hideFromRoles: ["faculty"],
        },
        description: "Student worker analytics.",
        icon: BarChart3,
      },
    ],
  },
  {
    id: "help",
    label: "Help & Resources",
    icon: BookOpen,
    description: "Guides and reference materials.",
    children: [
      {
        id: "help",
        label: "Tutorials",
        path: "help/tutorials",
        canonicalId: "help/tutorials",
        description: "Guided walkthroughs and tips.",
        icon: BookOpen,
      },
      {
        id: "baylor-systems",
        label: "Baylor Systems",
        path: "help/baylor-systems",
        canonicalId: "help/baylor-systems",
        description: "Links to Baylor systems.",
        icon: ExternalLink,
      },
      {
        id: "baylor-acronyms",
        label: "Acronyms",
        path: "help/acronyms",
        canonicalId: "help/acronyms",
        description: "Common terms and abbreviations.",
        icon: FileText,
      },
    ],
  },
  {
    id: "facilities",
    label: "Facilities",
    icon: Building,
    description: "Spaces, buildings, and temperature.",
    children: [
      {
        id: "space-management",
        label: "Spaces",
        path: "facilities/spaces",
        canonicalId: "facilities/spaces",
        description: "Space inventory and details.",
        icon: MapPin,
      },
      {
        id: "building-management",
        label: "Buildings",
        path: "facilities/buildings",
        canonicalId: "facilities/buildings",
        description: "Building information.",
        icon: Building,
      },
      {
        id: "temperature-monitoring",
        label: "Temperature",
        path: "facilities/temperature",
        canonicalId: "facilities/temperature",
        description: "Temperature monitoring.",
        icon: Thermometer,
      },
    ],
  },
  {
    id: "administration",
    label: "Administration",
    icon: Shield,
    description: "Imports, configuration, and access.",
    children: [
      {
        id: "smart-import",
        label: "Import Wizard",
        path: "admin-tools/import-wizard",
        canonicalId: "admin-tools/import-wizard",
        permissions: {
          hideFromRoles: ["faculty"],
        },
        description: "Import schedules and people data.",
        icon: Sparkles,
      },
      {
        id: "crn-tools",
        label: "CRN Quality Tools",
        path: "admin-tools/crn-tools",
        canonicalId: "admin-tools/crn-tools",
        permissions: {
          hideFromRoles: ["faculty"],
        },
        description: "Course data quality checks.",
        icon: Target,
      },
      {
        id: "access-control",
        label: "Access Control",
        path: "admin/access-control",
        canonicalId: "admin/access-control",
        adminOnly: true,
        description: "Roles and permissions.",
        icon: Shield,
      },
      {
        id: "app-settings",
        label: "App Settings",
        path: "admin/settings",
        canonicalId: "admin/settings",
        adminOnly: true,
        description: "Application configuration.",
        icon: Settings,
      },
      {
        id: "recent-changes",
        label: "Recent Changes",
        path: "admin/recent-changes",
        canonicalId: "admin/recent-changes",
        adminOnly: true,
        description: "Review recent updates.",
        icon: Clock,
      },
      {
        id: "data-hygiene",
        label: "Data Hygiene",
        path: "admin/data-hygiene",
        canonicalId: "admin/data-hygiene",
        adminOnly: true,
        description: "Cleanup tools and checks.",
        icon: FileText,
      },
    ],
  },
];
